### PR TITLE
Add AUR badge to readme

### PR DESCRIPTION
**Pull request by joshzcold**
I created an arch aur package for elasticvue, using the simple binary. 
https://aur.archlinux.org/packages/elasticvue-bin

### CODE REVIEW

**Comment by joshzcold** [comment]
Tell me if you want this in the pull request, but I created my own `.desktop` file since I don't think there is one? 

```
[Desktop Entry]

# The type as listed above
Type=Application

# The version of the desktop entry specification to which this file complies
Version=0.42.1

# The name of the application
Name=elasticvue

# A comment which can/will be used as a tooltip
Comment=Elasticsearch gui for your browser https://elasticvue.com

# The executable of the application, possibly with arguments.
Exec=elasticvue

# The name of the icon that will be used to display this entry
Icon=elasticvue

# Describes whether this application needs to be run in a terminal or not
Terminal=false

# Describes the categories in which this entry should be shown
Categories=Utility;Development

```

This is the aur package, but I wouldn't mind making another pull request with this getting brought into the build for the `.deb`

**Comment by cars10** [comment]
Hey, thanks for creating the package! In the future i would like to automatically publish packages on my own via CI, but for now this is great.

**Comment by cars10** [comment]
Hello @joshzcold , do you still maintain https://aur.archlinux.org/packages/elasticvue-bin ? It is quite outdated. Are you able to delete the package, or transfer ownership so i can manage it with up2date versions?

**Comment by joshzcold** [comment]
@cars10 yeah I don't anymore. Let me see how I can transfer ownership to you

**Comment by cars10** [comment]
@joshzcold did you have time to look into this? I have an AUR account, my user is named `cars10`, maybe you can transfer the package?

**Comment by joshzcold** [comment]
@cars10 You are now the sole maintainer

Thank you for a great application ♥️
image

**Pull request merged**
