### PR TITLE
Rework desktop app menu

### PR DESCRIPTION
**Pull request by itsgoingd**
Hey, this PR reworks the desktop app menu to contain all native menu items as expected, based on various examples I've found.

This fixes various keyboard shortcuts like copy, paste, select all, quit, etc.

It's my first time writing Rust so please review carefully. :) Tested only on MacOS.

### CODE REVIEW

**Comment by cars10** [comment]
Awesome, thanks! Can you please make sure that the testing instructions mentioned at the end of the [last release](https://github.com/cars10/elasticvue/releases/tag/v0.42.1) do work on macos?

**Comment by itsgoingd** [comment]
I'll check it out later today. Btw. I also have a Windows machine to test on, but no way to make a Windows build, is there any easy way to do it via the GitHub actions?

Btw. thanks for this very useful app! I'm implementing a large-scale Elastic project at work and using Elasticvue daily.

**Comment by cars10** [comment]
I can test it on windows & linux. There is a GH action to build elasticvue, but i am not sure if you are able to run it in a forked repo.

**Comment by itsgoingd** [comment]
Ah, nevermind then, thought you need help with testing on Windows as well.

Went through your testing checklist on a Mac build from develop branch:

- copy/paste - ✅ works great now
- saving files - ✅ does not work in `tauri:dev`, but works in the production build
- backup - ✅ same as above
- import - ✅ seems to work, but the list of clusters does not update without restarting the app
- cluster switching - ✅ works fine
- confirm messages - ✅ works fine

**Comment by cars10** [comment]
Awesome, thanks.

**Pull request merged**
