### PR TITLE
Feat: saving queries

### PR DESCRIPTION
**Pull request by enyosolutions**

### CODE REVIEW

**Comment by enyosolutions** [comment]
Tested locally 👍 

image

image

image


I reused the history object.
it would probably make sense to have another component, but i figured that this could suffice for now...


Let me know what you think.

**Comment by cars10** [comment]
Hey, thanks for your pr! I am busy rn but i will check as soon as i can.

**Comment by enyosolutions** [comment]
@cars10 any chance you could look into it ?

**Comment by cars10** [comment]
Sorry, i have to quarantine right now and do not have access to my development machine. Will take 1-2 weeks, but i can already tell you that this feature will most likely not make it into the next version of elasticvue (which is almost done) because it is quite big already. Sorry for the delay!

**Comment by enyosolutions** [comment]
@cars10 ok i understand. Let me know when the next version is live, and i'll update my merge request

**Comment by argentian** [comment]
hi，guys，i with my colleague using elasticvue ,it is very good feel;;; but slowly find inconvenience thing.
rest http can add some tabs like below picture，when i have a lot of request， i had to open a lot of windows，this window can add some “+”，when i click this “+” button,can open other tab,of course the tab can be close；
thank

**Comment by IgorBorovenkoCDW** [comment]
@cars10 , ability to save and load queries from files seems to be a killer feature as no other ES clients have it.

**Comment by cars10** [comment]
Whats wrong with using the history? you can favorite queries, filter ,etc

**Comment by IgorBorovenkoCDW** [comment]
> Whats wrong with using the history? you can favorite queries, filter ,etc

History and saving queries - are different types of experience. For example, any modern web browser has history, but it also has bookmarks.
Another reason - I might want to collaborate with my colleagues on a complex query and store it in Git.

**Comment by cars10** [comment]
This feature will be added in the upcoming 1.0 beta
image

**Comment by argentian** [comment]
It's cool!

**Pull request closed without merging**
