### PR TITLE
Support for env variables docker

### PR DESCRIPTION
**Pull request by tschallacka**
Hello, I know you're doing a massive rewrite of the entire library. I will work on a pull request for your current state of rewriting in develop as well.

For the current master, I've implemented these "useful changes" to allow environment variables for docker instances.

It allows auto connecting in the use in a docker compose network, just like phpmyadmin does.

From the readme:

For use in a docker compose configuration, you can connect to the elasticsearch instance in the docker compose network

You can now define the following environment variables:

* `ELASTICSEARCH_HOST` - The hostname of the elasticsearch instance (default: `localhost`)
* `ELASTICSEARCH_PORT` - The port of the elasticsearch instance (default: `9200`)
* `ELASTIC_CLIENT_TYPE` - The type of client to use (default: `default`)
    - `default` - The default client, connects via network.
    - `docker` - Connects to the elasticsearch instance in the docker compose network.
* `ELASTIC_USERNAME` - The username to use for authentication (default: ``)
* `ELASTIC_USERNAME` - The password to use for authentication (default: ``)
* `ELASTICVUE_AUTOCONNECT` - Automatically connect to the elasticsearch instance (default: `false`)
  - `true` - Automatically connect to the elasticsearch instance
  - `false` - Do not automatically connect to the elasticsearch instance

```yaml
version: '3.7'
services:
  app:
    build: .
    container_name: elasticvue
    networks:
      - elasticvue
    environment:
        - ELASTICSEARCH_HOST=http://elasticsearch
        - ELASTICSEARCH_PORT=9200
        - ELASTIC_CLIENT_TYPE=docker
        - ELASTIC_USERNAME=elastic
        - ELASTIC_PASSWORD=changeme
    restart: unless-stopped
    ports:
      - 8080:8080
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: unless-stopped
    networks:
      - elasticvue
    ports:
      - 9200:9200
      - 9300:9300
networks:
    elasticvue:
        driver: bridge

```

### Development of the docker variables implementation

An example of a docker network file is in docker-compose.elastic.yml. You can run it with

```bash
docker compose --file docker-compose.elastic.yml up --build -d
```

The most important part that enables the insertion of enviroment variables on starting the docker image without a rebuild
is in the file [100-replace-enviroment.sh](nginx/100-replace-enviroment.sh). It is executed on the start of the docker
and replaces the current environment values into the javascript compiled file, which is copied over fresh on the start
of the image.
If the order of the constants in the js file is changed, then the `search_str` and `replace_str` variables in this shell script need to be
updated as well.

### CODE REVIEW

**Comment by cars10** [comment]
Hey, thanks for taking the time to implement this. I will cherry pick some stuff for the currently ongoing rewrite :)

**Comment by aka-Ani** [comment]
This is a pretty cool effort! I also think the idea of "provisioning" the configuration in the deploy would be a neat feature, but I was wondering if it there is any benefit to doing it this env var way vs maybe trying to incorporate the already implemented import/export feature in Elasticvue. Like providing a config json in the docker compose environment section instead of individual params

**Comment by marcosdiez** [comment]
Since this code is exactly what I needed, I built a container with it here: https://hub.docker.com/r/marcosdiez/elasticvue

If one plans to use it KUBERNETES, set the environmental variable ELASTICVUE_PORT=8080 else the container will fail to launch. This happens because since my deployment is called "elasticvue", k8s automatically sets ELASTICVUE_PORT as something else which breaks everything

**Comment by nuno-andre** [comment]
Also, to be runable from the current directory (`./docker`):

```yaml
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
```

**Comment by cars10** [comment]
This will be fixed in https://github.com/cars10/elasticvue/issues/112

**Pull request closed without merging**
