### PR TITLE
feat: add support for building macOS app

### PR DESCRIPTION
**Pull request by qiwihui**
Using electron and electron-builder to build a macOS app.

### CODE REVIEW

**Comment by cars10** [comment]
Hey, thank you for contributing to elasticvue! I did not have the time to look into this yet because i am on vacation right now. But a question beforehand: does this also work on linux/windows for building an electron app, or is there anything mac specific?

**Comment by qiwihui** [comment]
This process works both for windows and linux. But I only have macOS to test output. We can simply add config for windows and linux to build app for these two platforms. Need some more time.

**Comment by corvino** [comment]
I'm curious why this got closed—it seems like a great idea. I pulled the branch and did my own build and definitely prefer having things wrapped in an app rather than dumped in with all my other browser tabs.

I am having a bit of an issue with cmd-R causing the web view to go blank, rather then either doing nothing or refreshing the current page. I was thinking of taking a look at this, but without a place for a fix to go it makes less sense.

I would echo what qiwihui said about Linux and Windows. It should be possible to test them in a virtual machine, but a more sensible approach seems to wait on someone wanting a build for one of those platforms and working through any issues. Having the Electron code in place and working on macOS should make a much better starting point for the other platforms, even if some work needs to be done there.

Can we reopen this? I'm happy to assist with testing and fixes as needed.

**Comment by cars10** [comment]
Hey @corvino , the user has closed this PR on his own. But i will explain my reasoning for not adding a desktop app yet:

Elasticvue is a web app, so the only way to create a useable cross-platform "desktop" app is to use electron - a stripped down chrome browser. I really don't see the benefit of opening _another_ browser instance that eats gigabytes worth of ram just to separate one tab from the others. I know that there are ways to use the more lightweight OS web rendering engine on windows (webview2) and macOS (WKWebView), but as i don't use either of these systems this is not really doable for me right now.
Aside from that: elasticvue can be installed in 6+ different ways and this already feels a bit too much, at least in terms of testing and release complexity.

Regardless, you are not the first user to ask for a desktop app. Because of that i plan to provide desktop apps for all major platforms in the future, hopefully in the next 2 or 3 versions :)

Regarding this PR: i will use the code as inspiration/starting point, but i will most likely change & restructure it a bit so it probably doesn't make sense to work on this right now. But it would be awesome if you could help testing the build & finished apps on macOS when it is done :)

Thanks for your input!

**Pull request closed without merging**
