### PR TITLE
Added arm64 support for docker

### PR DESCRIPTION
**Pull request by mikart143**
So the main problem is package called puppeteer. I made this one optional. I also added missing packages for builder in docker file.

As far as I know this image should be built using buildx not build command

### CODE REVIEW

**Comment by mikart143** [comment]
@cars10 the Issue for this pr is: #76

**Comment by cars10** [comment]
Thanks! I will check this in the next few days.

**Comment by cars10** [comment]
Can you explain why you need to add python and gcc? Are all of these really required, even at runtime?

**Comment by mikart143** [comment]
I was not able to build container because of node-sass which was looking for python. I found tip on the internet to instal those two. I am more of a backend guy

**Comment by cars10** [comment]
Thanks, i will try this :)

**Comment by cars10** [comment]
Closed, see #76

**Pull request closed without merging**
